### PR TITLE
Support i8 for long

### PR DESCRIPTION
**Pull request by ruhan1**

### CODE REVIEW

**Comment by jdcasey** [comment]
@ruhan1 is it possible to make the Long ValueType gracefully downgrade from i8 to int tags when decoding? I think Koji dynamically decides which to use based on the size of the number being sent, not on a notion of the constraints of the field it represents. IOW even if the field can accommodate 64-bit numbers, it'll use int if the value happens to be small enough.

**Comment by jdcasey** [comment]
We should always use Long on our side BTW... And I guess this means Kojiji will have to use Longs everywhere just in case

**Comment by ruhan1** [comment]
I look at Koji code and here is what they are doing:
`if (value > xmlrpc_client.MAXINT:
    write("<value><i8>")...
else:
    write("<value><int>")...`
In Kojiji we will get either an Integer or a Long. If the field type is Integer and the returned value is Long, or vice verse, we will get class cast exception. 
We can parse all i4/i8/int to Long object and switch Kojiji int fields to long. But this seems change a lot and break some users. 
The other way is to keep the Integer fields because mostly the value will be in the Integer scope. And only define Long fields when we really need it (such as file size), and handle the case when an Integer value is returned for this field (convert it to Long). This way we need not do a drastic change to Kojiji message objects.

**Comment by jdcasey** [comment]
In the cases where we're expecting a long (file size is a good example) but Koji returns an int, won't we need a special ValueType to handle that auto-conversion?

I'm fine with holding off on converting everything to long preemptively, mainly since it would cost quite a bit more in terms of memory usage to hold model objects. I'm just not sure how long we'll be able to do that. If Koji is being used more for high-frequency builds (like as part of a CI/CD solution), then taskId's and maybe even buildId's may exceed the 2 billion index mark soon, putting them into the realm of a long. It might be a good idea to try to get ahead of those things, even if we don't switch literally every int over to a long.

**Comment by ruhan1** [comment]
Besides the memory reason, handling all i4/i8/int as long seems ... not
elegant, if not ugly.

I updated the PR using an "upgrade cast" approach. We won't need to change
Kojiji at the moment. Users keep using it until they hit a
ClassCastException when Koji returns an i8 but the field is int. Then we
change the field to "long".

When Koji sends a small i4 to the Long field, we upgrade it to "long"
before setting it. Please review.

**Review by jdcasey — APPROVED** [review]

**Pull request merged**
